### ISSUE TITLE
Same input generate different html between viewer and editor

### ISSUE THREAD

**Issue by seb-saletes** [nhn/tui.editor#1045]
## Describe the bug
Html generated by viewer and editor are not consistent.

## To Reproduce
Input : `# Title\n`
html generated in editor: 
`<h1><div>Title</div><br></h1>`
html generated in viewer: 
`<h1>Title</h1>`

## Expected behavior
Editor and viewer should generate same html for same input. That way we can switch between mode without breaking style.

## Screenshots
[HTML generated by Editor](https://ibb.co/1GDqJt5)
[HTML generated by Viewer](https://ibb.co/wM4wvfG)

**Comment by seonim-ryu** [comment]
@seb-saletes This is not a problem with different tags. This is because the editor's default font family is not defined in the style used by the Viewer. Thanks for reporting the issue.

**Comment by seb-saletes** [comment]
Thanks for your quick reply.
I'm not sure to understand, what would be the editor output after the fix ?
Could you recommend a workaround until the fix land to release ?

**Comment by seonim-ryu** [comment]
@seb-saletes I think adding the `font-family` to the class selector below will make the Editor and Viewer style the same.

```css
.tui-editor-contents {
  font-family: 'Open Sans', 'Helvetica Neue', 'Helvetica', 'Arial', '나눔바른고딕', 'Nanum Barun Gothic', '맑은고딕', 'Malgun Gothic', sans-serif;
}
```
