### ISSUE TITLE
Disable/Remove image upload

### ISSUE THREAD

**Issue by iacobson** [nhn/tui.editor#1204]
## Summary
Is there a way to configure the editor / toolbar to show only the image url, but not the image file upload?

## Screenshots
<img width="515" alt="Screenshot 2020-09-17 at 16 42 51" src="https://user-images.githubusercontent.com/8473345/93487285-656cc000-f905-11ea-92e2-fe781280d8b6.png">

## Version
2.4

**Comment by nicodemuz** [comment]
I'm also looking for a solution to this. Is it possible to somehow pass custom template in here?
https://github.com/nhn/tui.editor/blob/a79dd97d453e62d3a3d858ec84fda6551572febf/apps/editor/src/js/ui/popupAddImage.js#L30

**Comment by seonim-ryu** [comment]
@iacobson 

There is currently no option to use that feature. The [template mentioned above](https://github.com/nhn/tui.editor/issues/1204#issuecomment-695160943) is also not exposed to the outside. So, an option should be added to the editor and I'll consider this.

**Comment by iacobson** [comment]
Thank you for the response and for considering the option!

**Comment by clll7** [comment]
wish

**Comment by EgoistDeveloper** [comment]
It is not a solution but it is fine to hide it if a special function is not assigned for the image upload tab.

Just add some CSS.

```css
/* TUI Editor show only image linking tab in popup */
.tui-editor-popup{
    box-shadow: 0px 0px 15px 5px rgba(0,0,0,0.26);
}

.te-popup-add-image .te-tab button, .te-popup-add-image .te-file-type{
	display: none !important;
}

.te-popup-add-image .te-url-type{
	display: block !important;
}
```  

Result:

![image](https://user-images.githubusercontent.com/17010054/103460649-f6d33700-4d28-11eb-991f-2054a159e289.png)

Actually there are to many issue, missing part and feature. I am using for comment form and this way acceptable for now.
