### ISSUE TITLE
Change background color of selected text

### ISSUE THREAD

**Issue by ndhhien27** [nhn/tui.editor#1482]
## Summary
I want to change the background color of selected text

## Screenshots
https://imgur.com/a/bXzmMqh

## Version
@toast-ui/react-editor: 2.5.3,
react: 16.10.2

## Additional context
I tried to change the background by `:selection` pseudo-element but it not work. Does someone have a solution for it?

**Comment by js87zz** [comment]
@ndhhien27 
Can you try as below?
```css
/* change the color what you want */
.CodeMirror-selected { background: blue !important; }
.CodeMirror-focused .CodeMirror-selected { background: blue !important;}
```
