### ISSUE TITLE
Chinese characters are not displaying well on the markdown preview

### ISSUE THREAD

**Issue by Bistard** [nhn/tui.editor#1733]
## Describe the bug
the Chinese characters are not displaying well on the markdown preview. 

## Screenshots
The below screenshot was testing on the given example website (https://nhn.github.io/tui.editor/3.0.2/tutorial-example01-editor-basic).
You can see some characters are seems displayed with bold and larger font size:
![image](https://user-images.githubusercontent.com/38385498/128188881-c078ebeb-551b-4feb-acff-6d8ac7e48a4a.png)

This is a screenshot from Typora with the same paragraph, texts seems normal.
![image](https://user-images.githubusercontent.com/38385498/128188793-4827aff4-2bd6-48de-a092-b23ad1062e67.png)

## Enviroment:
 - OS: windows 10
 - Browser: chrome
 - Version: 92.0.4515.131

## Additional context
I don't know if this is a bug or there is some config that I didn't find. If it is indeed a bug, is there any way that I can fix this by myself?

**Comment by Bistard** [comment]
Ok, I realize I can set font-family to fix this issue by myself:
```css
.toastui-editor-contents {
    font-family: "黑体","宋体", 'Open Sans', 'Helvetica Neue', 'Helvetica', 'Arial', '나눔바른고딕',
    'Nanum Barun Gothic', '맑은고딕', 'Malgun Gothic', sans-serif;
}
```
