### ISSUE TITLE
How to make custom HTML renderer work for paragraphs in WYSIWYG mode?

### ISSUE THREAD

**Issue by karleinarb** [nhn/tui.editor#1991]
## Summary
We are attempting to use ToastUI as an template creator/editor with placeholder-fields that will be replaced by other systems.
These placeholder-fields should be able to be inserted anywhere in the markdown so the $$Something $$ feature is not applicable.

We want to only use the WYSIWYG mode to make the user experience as smooth as possible.

Our plan is to be able to insert placeholders in this format anywhere in the markdown.
`{{label="Fullname":description="The recipients full name"}}`

A custom renderer should then look for the patterns and only render out a small chip showing the label-value.
The chip should have a onClick event to open a modal to edit the placeholder-data in an user friendly manner.

We are able to make the custom renderer work when in markdown-mode, but it does not run in WYSIWYG-mode.
We have not been able to find a way to register a onClick-event.

**Questions**

1. How can we make the custom renderer work in WYSIWYG mode?
2. How can we register a onClick-event for the custom HTML elements?

## Example code
```javascript
/*
  Custom HTML renderer
*/
function vtfkPlaceholderPlugin() {
  const toHTMLRenderers = {
    text() {
      const tags = [
        { type: 'openTag', tagName: 'span'},
        { type: 'text', content: 'Text before placeholder' },
        { type: 'closeTag', tagName: 'span' },
        { type: 'openTag', tagName: 'span', classNames:["placeholderChip"]},
        { type: 'text', content: '[PLACEHOLDER]', onClick: () => { alert('test'); } },
        { type: 'closeTag', tagName: 'span' },
        { type: 'openTag', tagName: 'span'},
        { type: 'text', content: 'Text after placeholder' },
        { type: 'closeTag', tagName: 'span' },
      ]
      return tags
    }
  }
  return { toHTMLRenderers }
}
```

```css
<!-- Chip styling -->
<style>
  .placeholderChip {
    cursor: pointer;
    border: 1px solid black;
    background-color: #B4DCDA;
    border-radius: 20px;
    font-weight: bold;
    margin-left: 0.2rem;
    margin-right: 0.2rem;
    padding: 0.2rem 0.5rem;
  }
</style>
```

## Screenshots
The renderer is working in markdown mode
![image](https://user-images.githubusercontent.com/45044399/140378411-674b2b93-96b6-4205-bf87-8856e96191c0.png)

But it is not working in WYSIWYG mode
![image](https://user-images.githubusercontent.com/45044399/140378813-47f4ee06-9ba4-4d9c-9e85-a18212b3d0a8.png)

## Version
We are using "@toast-ui/vue-editor": "^3.1.1"
