### ISSUE TITLE
Ordered List with Start Number

### ISSUE THREAD

**Issue by oraculum** [nhn/tui.editor#2173]
I would like to request a function to list numbered order.

In [commonmark has a spec](https://spec.commonmark.org/0.29/#lists) about Start Number List order.
![Screen Shot 2021-12-29 at 11 53 27](https://user-images.githubusercontent.com/470849/147674683-eb7ee4da-c0e8-452c-822b-ae37e3c43b9d.jpg)

something like this

![Screen Shot 2021-12-29 at 11 55 32](https://user-images.githubusercontent.com/470849/147674820-88a52e98-887f-4d40-8ab1-0f3dfde87047.jpg)

I try this in my tui.editor but it's not working 

![Screen Shot 2021-12-29 at 11 56 42](https://user-images.githubusercontent.com/470849/147675039-73f42e51-4689-4bb7-8794-8949646ce30e.jpg)

in preview 

![Screen Shot 2021-12-29 at 11 56 48](https://user-images.githubusercontent.com/470849/147675059-3171f03a-667d-4286-a8dd-143abff0d998.jpg)

it would be nice to have this feature suggested by CommonMark Spec

**Comment by js87zz** [comment]
@oraculum 
Sorry for late replying.
The cause of this problem is that we use the pseudo element to style list numbers. 
I'll think about how to improve this issue. Thank you for the report!

**Comment by coca-in-a-cola** [comment]
Hi! Faced this issue by myself, fixed for me by following scss code. Hope it'll help somebody

Actually it does the same thing @timesqueezer described: resets ol al ul overrides in favour of native ::marker behaviour

Note that checkboxes (task-list-item) were left untouched

Be careful in cocypasting because you'll need to override colors if you're using a dark theme
```scss

    .toastui-editor-contents {

      ol {
        list-style-type: decimal;
        counter-reset: unset;
      }

      ul {
        list-style-type: disc;
        counter-reset: unset;
      }

      ol > li {
        counter-increment: unset;
      }

      & ul > li:not(.task-list-item)::before,
      & ol > li::before {
        content: unset;
        display: none;
        position: unset;
      }

      ul > li::marker {
        margin-top: 6px;
        margin-left: -17px;
        width: 5px;
        height: 5px;
        border-radius: 50%;
        color: #ccc;
      }

      ol > li::marker {
        margin-left: -28px;
        width: 24px;
        color: #aaa;
      }
    }
```
