### ISSUE TITLE
fix: eslint num run build -> unsupported-css-property

### ISSUE THREAD

**Issue by Kyungseo-Park** [nhn/tui.editor#2932]
## Describe the bug

apps/editor/src/css/contents.css 경로의 CSS 스타일 문제
```css
.ProseMirror {
  font-family: 'Open Sans', 'Helvetica Neue', 'Helvetica', 'Arial', '나눔바른고딕',
    'Nanum Barun Gothic', '맑은고딕', 'Malgun Gothic', sans-serif;
  color: #222;
  font-size: 13px;
  overflow-y: auto;
  overflow-X: hidden; <-- Here 
  height: calc(100% - 36px);
}
```

▲ [WARNING] "overflow-X" is not a known CSS property [unsupported-css-property]

## To Reproduce

`npm run build.... ` ?...

## Screenshots
<img width="1034" alt="스크린샷 2023-01-29 오후 5 16 07" src="https://user-images.githubusercontent.com/45850400/215314073-2af483eb-502e-4ed8-85e7-177955d5bc39.png">

## Desktop (please complete the following information):
 - none

## Smartphone (please complete the following information):
 - none
