### ISSUE TITLE
scroll top when change heading or link in wysiwyg (3MD)

### ISSUE THREAD

**Issue by sohee-lee7** [nhn/tui.editor#444]
## Version
v1.3.3

## Test Environment

Chrome MacOS

## Current Behavior

Editor `height` option is `auto` and add property `.te-toolbar-section` for fix on top.
```css
.te-toolbar-section {
    top: 0;
    z-index: 5;
    position: sticky;
}
```
When change heading or link on the bottom, scrolling top occurs unintentionally.

## Expected Behavior

It should not be scrolled when change heading.
