### ISSUE TITLE
Diferent rendering of list between markdown and wysiwyg

### ISSUE THREAD

**Issue by NetDefender** [nhn/tui.editor#521]
## Version
1.4.1

## Test Environment

OS: Windows 10 x64
Browser: Opera

## Current Behavior
There is different rendering behaviour for ordered lists between markdown mode and html mode. I have this markdown:
```
1. aaa
2. bbb
    1. ccc
    2. ddd
3. eee
```
and in markdown mode the preview html generated is:
```
<ol>
	<li>aaa</li>
	<li>bbb
		<ol>  <!-- look at this element -->
			<li>ccc</li>
			<li>ddd</li>
		</ol>
	</li>
	<li>eee</li>
</ol>
```
which is correct. If i switch to wysiwyg mode the html mode converts to:

```
<ol>
	<li>aaa</li>
	<li>bbb</li>
		<ol> <!-- look at this element -->
			<li>ccc</li>
			<li>ddd</li>
		</ol>
	<li>eee<br></li>
</ol>
```
The second ol has been moved away. The code that change the html in wysiwyg mode is inside **wwListManager.js**:

```js
/**
   * make arbitrary nesting list out of standard list
   * `<ul><li>text<ul><li>text2</li></ul></li></ul>` to
   * `<ul><li>text</li><ul><li>text2</li></ul></ul>`
   * @param {string} html string to convert
   * @returns {string} converted HTML text
   * @private
   */
  _convertToArbitraryNestingList(html) {
    const NESTED_LIST_QUERY = 'li > ul, li > ol';
    const wrapper = document.createElement('div');
    wrapper.innerHTML = html;

    let nestedList = wrapper.querySelector(NESTED_LIST_QUERY);
    while (nestedList !== null) {
      const parentLI = nestedList.parentNode;
      const parentList = parentLI.parentNode;

      parentList.insertBefore(nestedList, parentLI.nextElementSibling);

      nestedList = wrapper.querySelector(NESTED_LIST_QUERY);
    }

    return wrapper.innerHTML;
  }
```

if i comment the code and return the html without processing looks like it works fine. Is it any reason for calling this method? Is it for editing purposes? Many thanks in advance. It is a wonderful component.

I need this to be the same because i have created a css to renumber the items:

```css
.tui-editor-contents ol:not(.footnotes-list) {
    list-style-type: none;
    counter-reset: item;
    margin: 0;
    padding: 0;
}

.tui-editor-contents ol:not(.footnotes-list) > li {
    display: table;
    counter-increment: item;
    margin-bottom: 0.6em;
    text-align: justify;
}

.tui-editor-contents ol:not(.footnotes-list) > li:before {
    content: counters(item, ".") ". ";
    display: table-cell;
    padding-right: 0.6em;
}

.tui-editor-contents li ol:not(.footnotes-list) > li {
    margin: 0;
}

.tui-editor-contents li ol:not(.footnotes-list) > li:before {
    content: counters(item, ".") " ";
}
```
that result in the following html and looks great:

![Captura](https://user-images.githubusercontent.com/2451916/58751743-19450480-84a3-11e9-9a43-86c53aded6c6.PNG)

## Expected Behavior
List should be rendered the same way in preview mode and wysiwyg mode.
