### ISSUE TITLE
Toolbar menu is hidden

### ISSUE THREAD

**Issue by taurenshaman** [nhn/tui.editor#531]
Toolbar menu (heading, table) is hidden. Others is ok including inserting image or link.
Please have a look at here: https://codepen.io/taurenshaman/pen/vwMvXY

The front framework is this: https://metroui.org.ua/index.html

Thank you very much!

**Comment by sohee-lee7** [comment]
This issue is odd but if you set bellow css, this issue will be resolved.
```css
.tui-editor-defaultUI-toolbar {
  overflow: visible;
}
```
