### ISSUE TITLE
Cannot add text via SendKeys from opentest

### ISSUE THREAD

**Issue by bluecatchbird** [nhn/tui.editor#657]
## Version
- 1.4.6

## Test Environment
| name | version |
|----|----|
| OS debian | 9| 
| firefox | 60.9.0 |
| opentest | 1.1.4 |

## Current Behavior

I test my webapplication with [opentest](https://github.com/mcdcorp/opentest) and i want touse it to write into the toast ui editor.
But i cannot send Click or Key Events with opentest to the editor.

This opentest step i use to send key events:
```
- description: add content to editor
  action: org.getopentest.selenium.SendKeys
  args:
    locator: { css: "div.cm-s-default textarea" }
    text: test content
```
The error message from opentest:
```
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for element to be clickable: [[FirefoxDriver: firefox on LINUX (7bbfcc01-e8d7-4ee7-8a78-f033d8ffb30f)] -> css selector: div.cm-s-default textarea] (tried for 10 second(s) with 500 milliseconds interval)
```

## Expected Behavior

The SendKeys method should work for the editor as for any other html textarea field.
