### ISSUE TITLE
No syntax highlighting in WYSIWYG mode

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [nhn/tui.editor#69]
## Version
1.0.2

## Test Environment
Mozilla Firefox Dev Edition (latest), nw.js (latest webkit)

## Current Behavior

Open https://nhnent.github.io/tui.editor/

Write some code, like 

    ```css
     .tui-editor-defaultUI .te-tab button {
        box-sizing: border-box;
        line-height: 100%;
        position: relative;
        cursor: pointer;
        z-index: 1;
    }
    ```

While in Markdown mode, the preview code is colored. While in WUSIWYG, it is not.

## Expected Behavior

Code should be colored in both views.
